import argparse
import json
import glob
import logging
import os
import re

from ura_xlaw.config import PATHS

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')
logger = logging.getLogger(__name__)

def clean_body_text(text: str) -> str:
    """Clean PDF artifacts and normalize whitespace in document body."""
    if not text:
        return ""

    # Remove code blocks artifacts (sometimes generated by PyMuPDF)
    text = re.sub(r'```[^+]*\+', '', text)
    
    # Remove page numbers (e.g., "1 \n \n", "2 \n \n", etc.)
    text = re.sub(r'\d+\s+\n\s+\n', '\n', text)
    
    # Normalize multiple newlines into double newlines for paragraph separation
    text = re.sub(r'\n\s*\n+', '\n\n', text)
    
    # Normalize internal spaces (but keep double newlines)
    lines = [line.strip() for line in text.split('\n')]
    text = '\n'.join(lines)
    text = re.sub(r' +', ' ', text)
    
    # Final trim
    return text.strip()

def process_dataset(raw_dir: str, output_path: str):
    """Scan raw directory, merge batches, deduplicate, clean and save as JSONL."""
    json_files = glob.glob(os.path.join(raw_dir, "*.json"))
    logger.info(f"Found {len(json_files)} batch files in {raw_dir}")

    all_docs = {}  # Use dict for deduplication by doc_id
    total_raw_count = 0

    for file_path in json_files:
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
                if not isinstance(data, list):
                    continue
                
                for item in data:
                    doc_id = item.get('id') or item.get('doc_id')
                    if not doc_id:
                        continue
                    
                    total_raw_count += 1
                    
                    # Store if new or merging strategy (we take the first one found)
                    if doc_id not in all_docs:
                        # Clean the body
                        item['body_cleaned'] = clean_body_text(item.get('body', ""))
                        all_docs[doc_id] = item
        except Exception as e:
            logger.error(f"Error reading {file_path}: {e}")

    logger.info(f"Total raw items processed: {total_raw_count}")
    logger.info(f"Unique documents after deduplication: {len(all_docs)}")

    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Save as JSONL
    count_saved = 0
    with open(output_path, 'w', encoding='utf-8') as f_out:
        for doc_id in sorted(all_docs.keys(), key=lambda x: int(x) if x.isdigit() else x):
            f_out.write(json.dumps(all_docs[doc_id], ensure_ascii=False) + '\n')
            count_saved += 1

    logger.info(f"Successfully saved {count_saved} cleaned documents to {output_path}")

def main() -> None:
    parser = argparse.ArgumentParser(description="Clean and deduplicate judgments.")
    parser.add_argument("--input", default=str(PATHS.raw_judgments))
    parser.add_argument("--output", default=str(PATHS.cleaned_judgments))
    args = parser.parse_args()
    process_dataset(args.input, args.output)


if __name__ == "__main__":
    main()
